### ISSUE TITLE
Javascript SIRI requests

### ISSUE THREAD

**Issue by Jees1** [barbeau/awesome-transit#189]
So, is there no way to request Bus Monitoring via JS in the SIRI protocol?

**Comment by barbeau** [comment]
@Jees1 If you're asking if I know about any open-source libraries projects for SIRI clients in Javascript, no, unfortunately I don't.

**Comment by Jees1** [comment]
found a solution to what i was making, thanks!

**Comment by barbeau** [comment]
@Jees1 Great! Could you share what you found?

**Comment by Jees1** [comment]
Found a REST api for the system
