### ISSUE TITLE
Please consider adding timetable_kit to GTFS Timetable Publishing Tools 

### ISSUE THREAD

**Issue by neroden** [barbeau/awesome-transit#212]
An open source Python 3.10 module and scripts depending on GTFS Kit, designed to create complex printed/PDF timetables with flexible layouts. Currently only working out of the box for Amtrak's GTFS, but under active development.

https://github.com/neroden/timetable_kit

**Comment by barbeau** [comment]
@neroden Thanks! Could you open a pull request please?
