### ISSUE TITLE
Add New API's to Awesome-Transit

### ISSUE THREAD

**Issue by Simha-Kalimipalli** [barbeau/awesome-transit#237]
Hi there,
I have identified a set of APIs that should be added to Awesome transit:

https://github.com/Simha-Kalimipalli/Urbanism-Links/blob/main/Github/Github_Urbanism_Links.md

Thanks

**Comment by carlfredl** [comment]
@Simha-Kalimipalli awesome! This looks like a more general list of links related to urban planning and tranportation. Are there specific APIs you suggest we add?

**Comment by Simha-Kalimipalli** [comment]
I've added several visualization related APIs to awesome-transit in prior commits ( see https://github.com/MobilityData/awesome-transit/pull/239) but I'm still figuring out the best place to add several of the tools (see  https://github.com/MobilityData/awesome-transit/issues/238)

**Comment by carlfredl** [comment]
Excellent. Closing this issue as it seems like the remaining improvements are captured in #238
