### ISSUE TITLE
Add transitous to this list

### ISSUE THREAD

**Issue by isabelle-dr** [barbeau/awesome-transit#242]
Add the https://github.com/public-transport/transitous project. 
Referencing a message on MobilityData's slack: 

> 
At fosdem2024 a group of volunteers started [transitous](https://github.com/public-transport/transitous) which strives for Europe wide transit routing based on opendata and opensource ([motis](https://motis-project.de/)).

**Comment by isabelle-dr** [comment]
@jbruechert, @vkrause, @EdwardBetts, do you want to open a PR to add this awesome project in this list? 

:)

**Comment by vkrause** [comment]
We can certainly do that, although I'd maybe wait a bit until there's more to show :) Which section would this belong into though? It's somewhere between "Software for Creating APIs" and "Apps".

**Comment by isabelle-dr** [comment]
We will be re-organizing some of these sections, so you can pick one that _kind of works_ and it will be perfect :)

Thank you for making this project available to the community 🤩
